---
- include: query_instance.yml

- name: Set ec2_info
  set_fact:
    ec2_info: []

- name: Add running instance to ec2_info
  set_fact:
    ec2_info: "{{ec2_info}} + [{{item}}]"
  with_items: "{{ec2_info_s}}"
  loop_control:
    label: "id: {{item.instance_id}}, hostname: {{item.public_dns_name}}, private_ip: {{item.private_ip_address}}, az: {{item.placement.availability_zone}}"
  when: item.state.name in ['running']

- name: Check any non-running instances
  fail:
    msg: "can not configure a non-running instance, please make sure all instances are running first"
  when: ec2_info|length < ec2_info_s|length

- include: "add_subnet_with_{{my_profile_name}}.yml"
  when: subnet_ids|length == 0

- include: inventory.yml                # add hosts to in-memory inventory
  when: ec2_info|length > 0

- include: create.yml                   # create instances if they are not there
  when: ec2_info|length == 0

- include: query_sg.yml

- name: Set ec2_subnet_info
  set_fact:
    ec2_subnet_info: []

- include: query_subnet.yml
  vars:
    my_subnet_ids: "{{subnet_ids}}"

- name: Set ec2_profile
  set_fact:
    ec2_profile: "{{profile}}"

- name: Set ec2_sg_rules
  set_fact:
    ec2_sg_rules: "{{sg_rules}} + {{extra_sg_rules}}"
