---
- name: Get ec2 subnet facts with profile (boto3 and Ansible 2.5+ required)
  ec2_vpc_subnet_facts:
    profile: "{{profile}}"
    security_token: "{{session_token|default(None)}}"
    region: "{{region}}"
    subnet_ids: "{{my_subnet_ids}}"
  register: ec2_subnet_info_p

- name: Add subnet to ec2_subnet_info with profile in {{region}}
  set_fact:
    ec2_subnet_info: "{{ec2_subnet_info}} + [{{item}}]"
  with_items: "{{ec2_subnet_info_p.subnets}}"
  loop_control:
    label: "{{item.id}}: {{item.cidr_block}}"
