---
- name: Set ec2_sg_info
  set_fact:
    ec2_sg_info: []
  when: ec2_sg_info is not defined

- name: Get ec2 security group facts with profile (boto3 required)
  ec2_group_facts:
    profile: "{{profile}}"
    security_token: "{{session_token|default(None)}}"
    region: "{{region}}"
    filters:
      vpc_id: "{{vpc_id}}"
      group_name: "{{sg_name|default(key_name + '_sg')}}"
  register: ec2_sg_info_p

- name: Add sg to ec2_sg_info with profile in {{region}}
  set_fact:
    ec2_sg_info: "{{ec2_sg_info}} + [{{item}}]"
  with_items: "{{ec2_sg_info_p.security_groups}}"
  loop_control:
    label: "{{item.group_name}}: {{item.group_id}}"
  when: ec2_sg_info_p.security_groups is defined and ec2_sg_info_p.security_groups|length > 0
